### ISSUE TITLE
pytest_html_merger

### ISSUE THREAD

**Issue by akavbathen** [szabgab/code-maven.com#150]
https://code-maven.com/combine-pytest-reports

Hi 👋 

I have decided to develop a utility that is able to merge several pytest-html reports. 
Very useful to those running pytest suites in parallel and want to combine the reports later.

**Check it out:**
https://github.com/akavbathen/pytest_html_merger

Please open an Issue or contribute directly by creating a PR

**Enjoy!**

**Comment by JainSiddhant** [comment]
Good Work..
I am facing an issue while using it.
 > pytest_html_merger -i reports/ -o reports/report.html
(base) siddhanj-mac:reports siddhanj$ ls
test1.html	test2.html

I see following error ;
(base) siddhanj-mac:reports siddhanj$ pytest_html_merger -i reports/ -o reports/report.html
Traceback (most recent call last):
  File "/Users/siddhanj/anaconda3/bin/pytest_html_merger", line 8, in <module>
    sys.exit(main())
  File "/Users/siddhanj/anaconda3/lib/python3.7/site-packages/pytest_html_merger/main.py", line 185, in main
    merge_html_files(args.input, args.output)
  File "/Users/siddhanj/anaconda3/lib/python3.7/site-packages/pytest_html_merger/main.py", line 22, in merge_html_files
    raise RuntimeError(f"Was unable to find html files in {in_path}")
RuntimeError: Was unable to find html files in reports/

**Comment by akavbathen** [comment]
Hi,

Thanks for your email.
Could you please send me ls output on reports directory? Looks like
test1.html and  test2.html are located under CWD which  is one level above
reports directory.

Best Regards,
Bat Hen
